version: '3'
services:

  db:
    restart: always
    image: postgres:alpine
### Uncomment to enable DB persistance
    volumes:
      - /srv/mastodon/vulpine.club/postgres:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
### Uncomment to enable REDIS persistance
    volumes:
      - /srv/mastodon/vulpine.club/redis:/data

  web:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    environment:
      - WEB_CONCURRENCY=2
      - MAX_THREADS=15
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - /srv/mastodon/vulpine.club/public/assets:/mastodon/public/assets
      - /srv/mastodon/vulpine.club/public/packs:/mastodon/public/packs
      - /srv/mastodon/vulpine.club/public/system:/mastodon/public/system

  streaming:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: npm run start
    ports:
      - "127.0.0.1:4000:4000"
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    image: gargron/mastodon
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -c 10 -q default -q mailers -q push
    depends_on:
      - db
      - redis
    volumes:
      - /srv/mastodon/vulpine.club/public/system:/mastodon/public/system

  sidekiq_pull:
    restart: always
    build: .
    image: gargron/mastodon
    env_file: .env.production
    command: bundle exec sidekiq -c 10 -q pull
    depends_on:
      - db
      - redis
    volumes:
      - /srv/mastodon/vulpine.club/public/system:/mastodon/public/system

  # for things like pg_dump, etc.
  dbmaint:
    #restart: no
    image: postgres:alpine
    command: /bin/true
    depends_on:
      - db
    volumes:
      - /srv/mastodon/vulpine.club/pg_dump:/dump
