version: '2'
services:
  db:
    restart: always
    image: postgres:alpine
  redis:
    restart: always
    image: redis:alpine
  web:
    restart: always
    build: .
    env_file: .env.production
    environment:
      - WEB_CONCURRENCY=2
      - MAX_THREADS=15
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - /srv/mastodon/vulpine.club/public/assets:/mastodon/public/assets
      - /srv/mastodon/vulpine.club/public/system:/mastodon/public/system
  streaming:
    restart: always
    build: .
    env_file: .env.production
    command: npm run start
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
  sidekiq:
    restart: always
    build: .
    env_file: .env.production
    command: bundle exec sidekiq -c 15 -q default -q mailers -q pull -q push
    depends_on:
      - db
      - redis
    volumes:
      - /srv/mastodon/vulpine.club/public/system:/mastodon/public/system
